FROM node:8-alpine AS builder
WORKDIR /app
ADD . /app
RUN npm config set registry https://registry.npm.taobao.org
RUN npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
RUN npm install @vehiclecloud/mongo-rest-client  --registry=http://nexus.agthings.cn:8081/repository/npm-all/
RUN npm install --registry=https://registry.npm.taobao.org
RUN ["npm", "run", "build"]

FROM nginx:alpine
COPY --from=builder /app/dist/ /usr/share/nginx/html/
